local source = debug.getinfo(1, "S").source:sub(2)
local root = source:match("^(.*)/tests/[^/]+$") or "."
local core = dofile(root .. "/layout/core.lua")
local overview = dofile(root .. "/layout/overview.lua")
local json = dofile(root .. "/layout/json.lua")
local config = { peek_x = 24, peek_y = 24, gap_x = 6, gap_y = 6,
    width_steps = { 0.5, 0.9, 1 }, height_steps = { 0.5, 0.9, 1 }, default_width_step = 2, default_height_step = 3 }
local area = { x = 2560, y = 26, w = 1920, h = 1054 }
local state = core.new_state()
core.sync(state, { "A", "B", "C", "D", "E" }, "A", config)
local session = overview.open(state)
local before = json(state)
assert(overview.navigate(core, state, session, "right"))
assert(session.selected_id == "B" and session.camera.col == 0)
assert(overview.navigate(core, state, session, "right"))
assert(session.selected_id == "C" and session.camera.col == 1)
assert(json(state) == before, "overview navigation changed real focus, sizes, camera, or positions")
assert(not overview.navigate(core, state, session, "invalid"))
local normal = core.placements(state, area, config)
local captured = overview.capture_placements(normal, area)
for id, box in pairs(captured) do
    assert(box.x >= area.x and box.x + box.w <= area.x + area.w)
    assert(box.y >= area.y and box.y + box.h <= area.y + area.h)
    assert(box.w == normal[id].w and box.h == normal[id].h, "capture resized an application")
    for _, value in pairs(box) do assert(value == math.floor(value), "capture used fractional geometry") end
end
overview.placements(core, state, session, area, config)
assert(json(state) == before, "preview geometry changed real layout")
overview.finish(core, state, session, true)
assert(state.focused_id == "C" and state.camera.col == 2)
core.pan(state, "down")
core.pan(state, "left")
local original = json(state)
session = overview.open(state)
overview.navigate(core, state, session, "right")
overview.finish(core, state, session, false)
assert(json(state) == original, "Escape failed to restore a manually panned camera")
session = overview.open(state)
assert(overview.finish(core, state, session, true, "E") == "E", "click did not select requested window")
assert(state.camera.col == 4)
session = overview.open(state)
assert(overview.finish(core, state, session, true, "missing") == nil)
core.sync(state, { "A", "B", "C", "D" }, nil, config)
overview.sync(state, session)
assert(state.positions[session.selected_id], "closed selection was not removed")
overview.finish(core, state, session, false)
assert(state.camera.col == 4, "closing the original window lost the saved camera")
core.sync(state, {}, nil, config)
assert(overview.open(state) == nil)
assert(json('a"\\\n\t') == '"a\\"\\\\\\u000a\\u0009"', "JSON string escaping failed")
print("ok - overview navigation, capture, confirmation, cancellation, and window lifecycle")
